"""
Additional Medical Terms - 550+ new term → plain English pairs
==============================================================
These supplement the ~325 terms in build_training_data_v2.py.
No duplicates with existing MEDICAL_TERMS dictionary.

Categories:
  1. Clinical abbreviations (75+)
  2. Medication classes and common drugs (80+)
  3. Clinical phrases from discharge papers (70+)
  4. Conditions and diagnoses (90+)
  5. Surgical and procedural terms (70+)
  6. Radiology and imaging terms (40+)
  7. Additional labs, vitals, and nursing terms (60+)
  8. Additional anatomy and physical exam terms (65+)
"""

ADDITIONAL_MEDICAL_TERMS = {

    # =================================================================
    # 1. CLINICAL ABBREVIATIONS (75+)
    # =================================================================
    "SOB": "shortness of breath",
    "DOE": "shortness of breath with physical activity",
    "BLE": "both legs",
    "BUE": "both arms",
    "RLE": "right leg",
    "LLE": "left leg",
    "RUE": "right arm",
    "LUE": "left arm",
    "UE": "upper extremity (arm)",
    "LE": "lower extremity (leg)",
    "ROS": "review of systems, a checklist of symptoms the doctor asks about",
    "HPI": "history of present illness, the story of why the patient came in",
    "PMH": "past medical history",
    "PSH": "past surgical history",
    "FH": "family history",
    "SH": "social history (smoking, alcohol, drug use, living situation)",
    "CC": "chief complaint, the main reason for the visit",
    "DDx": "differential diagnosis, a list of possible causes",
    "Dx": "diagnosis",
    "Tx": "treatment",
    "Rx": "prescription",
    "Hx": "history",
    "Sx": "symptoms",
    "Fx": "fracture (broken bone)",
    "Bx": "biopsy",
    "Cx": "culture (lab test to grow and identify germs)",
    "WNL": "within normal limits",
    "NAD": "no acute distress (the patient does not appear to be in pain or danger)",
    "HEENT": "head, eyes, ears, nose, and throat exam",
    "PERRLA": "pupils are equal, round, and react to light normally",
    "RRR": "regular rate and rhythm (the heart sounds normal)",
    "CTA b/l": "clear to auscultation bilaterally (both lungs sound clear with stethoscope)",
    "CTAB": "clear to auscultation bilaterally (both lungs sound clear)",
    "NT/ND": "non-tender and non-distended (belly is not painful and not bloated)",
    "A&O": "alert and oriented (awake and aware of surroundings)",
    "AAOx3": "awake, alert, and oriented to person, place, and time",
    "AAOx4": "awake, alert, and oriented to person, place, time, and situation",
    "VSS": "vital signs stable",
    "T max": "the highest temperature recorded",
    "HR": "heart rate",
    "BP": "blood pressure",
    "RR": "respiratory rate (number of breaths per minute)",
    "SpO2": "blood oxygen level measured by a finger sensor",
    "I/O": "intake and output (tracking fluids going in and coming out)",
    "UOP": "urine output",
    "BMI classification": "body mass index categories used to assess if weight is healthy for height",
    "LOS": "length of stay (how many days in the hospital)",
    "AMA": "against medical advice (the patient chose to leave before the doctor recommended)",
    "D/C": "discharge or discontinue",
    "f/u": "follow up",
    "w/u": "workup (tests and exams to figure out a diagnosis)",
    "H&P": "history and physical exam",
    "c/o": "complaining of",
    "r/o": "rule out (testing to exclude a possible diagnosis)",
    "WDWN": "well-developed, well-nourished (the patient appears healthy in build and nutrition)",
    "NKDA": "no known drug allergies",
    "NKA": "no known allergies",
    "Pt": "patient",
    "yo": "year old",
    "y/o": "year old",
    "M": "male",
    "F": "female",
    "h/o": "history of",
    "w/": "with",
    "w/o": "without",
    "c/w": "consistent with (matches what we would expect)",
    "s/s": "signs and symptoms",
    "STAT": "immediately, right now",
    "OR": "operating room",
    "ER": "emergency room",
    "ED": "emergency department",
    "PACU": "post-anesthesia care unit (the recovery room after surgery)",
    "OOB": "out of bed",
    "ADLs": "activities of daily living (bathing, dressing, eating, toileting)",
    "SNF": "skilled nursing facility (a nursing home with medical care)",
    "LTAC": "long-term acute care hospital",
    "PCP": "primary care physician (your regular doctor)",

    # =================================================================
    # 2. MEDICATION CLASSES AND COMMON DRUGS (80+)
    # =================================================================
    # --- Drug classes ---
    "beta-blocker": "a medication that slows the heart rate and lowers blood pressure",
    "beta-blockers": "medications that slow the heart rate and lower blood pressure",
    "ACE inhibitor": "a blood pressure medication that relaxes blood vessels",
    "ACE inhibitors": "blood pressure medications that relax blood vessels",
    "ARB": "angiotensin receptor blocker, a blood pressure medication similar to ACE inhibitors",
    "calcium channel blocker": "a medication that relaxes blood vessels and slows the heart",
    "statin": "a cholesterol-lowering medication",
    "statins": "cholesterol-lowering medications",
    "SSRI": "a type of antidepressant that increases serotonin in the brain",
    "SSRIs": "antidepressants that increase serotonin in the brain",
    "SNRI": "a type of antidepressant that increases serotonin and norepinephrine",
    "benzodiazepine": "a sedative medication used for anxiety, seizures, or sleep",
    "benzodiazepines": "sedative medications used for anxiety, seizures, or sleep",
    "opioid": "a strong pain medication that can be habit-forming",
    "opioids": "strong pain medications that can be habit-forming",
    "NSAID": "a non-steroidal anti-inflammatory drug like ibuprofen that reduces pain and swelling",
    "NSAIDs": "anti-inflammatory pain medications like ibuprofen and naproxen",
    "PPI": "proton pump inhibitor, a medication that reduces stomach acid",
    "PPIs": "proton pump inhibitors, medications that reduce stomach acid",
    "H2 blocker": "a medication that reduces stomach acid production",
    "antiplatelet": "a medication that prevents blood cells from clumping together",
    "antihypertensive": "a medication used to lower blood pressure",
    "antiarrhythmic": "a medication used to control irregular heart rhythms",
    "anticonvulsant": "a medication used to prevent seizures",
    "antipsychotic": "a medication used to treat severe mental health conditions like psychosis",
    "corticosteroid": "a strong anti-inflammatory medication",
    "corticosteroids": "strong anti-inflammatory medications (like prednisone)",
    "antihistamine": "a medication that treats allergic reactions",
    "laxative": "a medication that helps with constipation",
    "muscle relaxant": "a medication that reduces muscle spasms and tightness",
    "sedative": "a medication that causes drowsiness and calmness",
    "hypnotic": "a medication used to help with sleep",
    "thrombolytic": "a clot-busting medication given during a heart attack or stroke",
    "antifungal": "a medication that treats fungal infections",
    "antiviral": "a medication that treats viral infections",
    "biologic": "a medication made from living cells that targets specific parts of the immune system",

    # --- Specific common drugs patients see on discharge papers ---
    "metoprolol": "a beta-blocker that slows the heart rate and lowers blood pressure",
    "atenolol": "a beta-blocker that slows the heart rate and lowers blood pressure",
    "carvedilol": "a beta-blocker used for heart failure and high blood pressure",
    "lisinopril": "an ACE inhibitor that lowers blood pressure by relaxing blood vessels",
    "enalapril": "an ACE inhibitor used to treat high blood pressure and heart failure",
    "losartan": "an ARB medication that lowers blood pressure",
    "valsartan": "an ARB medication used for high blood pressure and heart failure",
    "amlodipine": "a calcium channel blocker that lowers blood pressure",
    "diltiazem": "a calcium channel blocker that slows heart rate and lowers blood pressure",
    "atorvastatin": "a statin medication that lowers cholesterol (brand name Lipitor)",
    "rosuvastatin": "a statin medication that lowers cholesterol (brand name Crestor)",
    "simvastatin": "a statin medication that lowers cholesterol (brand name Zocor)",
    "aspirin": "a blood-thinning and pain-relieving medication",
    "clopidogrel": "a blood thinner that prevents blood clots (brand name Plavix)",
    "ticagrelor": "a blood thinner often given after a heart stent (brand name Brilinta)",
    "warfarin": "a blood thinner that requires regular blood tests to monitor (brand name Coumadin)",
    "apixaban": "a blood thinner that does not require regular blood tests (brand name Eliquis)",
    "rivaroxaban": "a blood thinner taken by mouth (brand name Xarelto)",
    "enoxaparin": "an injectable blood thinner given as a shot under the skin (brand name Lovenox)",
    "heparin": "an injectable blood thinner given through an IV or shot",
    "furosemide": "a diuretic (water pill) that removes excess fluid (brand name Lasix)",
    "spironolactone": "a mild diuretic that also helps the heart (brand name Aldactone)",
    "hydrochlorothiazide": "a diuretic (water pill) used to treat high blood pressure",
    "metformin": "a diabetes medication that lowers blood sugar (brand name Glucophage)",
    "glipizide": "a diabetes pill that helps the pancreas release more insulin",
    "insulin glargine": "a long-acting insulin taken once daily (brand name Lantus)",
    "insulin lispro": "a fast-acting insulin taken before meals (brand name Humalog)",
    "omeprazole": "a proton pump inhibitor that reduces stomach acid (brand name Prilosec)",
    "pantoprazole": "a proton pump inhibitor that reduces stomach acid (brand name Protonix)",
    "ondansetron": "an anti-nausea medication (brand name Zofran)",
    "promethazine": "a medication used for nausea and allergic reactions (brand name Phenergan)",
    "gabapentin": "a medication for nerve pain and seizures (brand name Neurontin)",
    "pregabalin": "a medication for nerve pain, seizures, and anxiety (brand name Lyrica)",
    "sertraline": "an SSRI antidepressant (brand name Zoloft)",
    "fluoxetine": "an SSRI antidepressant (brand name Prozac)",
    "escitalopram": "an SSRI antidepressant (brand name Lexapro)",
    "duloxetine": "an SNRI antidepressant also used for nerve pain (brand name Cymbalta)",
    "trazodone": "a medication used for sleep and depression",
    "lorazepam": "a benzodiazepine used for anxiety and seizures (brand name Ativan)",
    "diazepam": "a benzodiazepine used for anxiety, seizures, and muscle spasms (brand name Valium)",
    "oxycodone": "a strong opioid pain medication (brand name OxyContin or Percocet when combined with acetaminophen)",
    "hydrocodone": "a strong opioid pain medication (found in Norco and Vicodin)",
    "morphine": "a strong opioid pain medication used for severe pain",
    "tramadol": "a mild opioid-like pain medication (brand name Ultram)",
    "acetaminophen": "a common pain reliever and fever reducer (brand name Tylenol)",
    "ibuprofen": "an anti-inflammatory pain reliever (brand name Advil or Motrin)",
    "naproxen": "an anti-inflammatory pain reliever (brand name Aleve)",
    "ketorolac": "a strong anti-inflammatory pain medication given by injection (brand name Toradol)",
    "amoxicillin": "a common antibiotic used for many types of infections",
    "augmentin": "an antibiotic combining amoxicillin with a booster to treat resistant bacteria",
    "azithromycin": "an antibiotic often used for respiratory and ear infections (brand name Z-pack)",
    "ciprofloxacin": "a strong antibiotic used for urinary and abdominal infections (brand name Cipro)",
    "levofloxacin": "a strong antibiotic used for pneumonia and urinary infections (brand name Levaquin)",
    "doxycycline": "an antibiotic used for skin, respiratory, and tick-borne infections",
    "cephalexin": "an antibiotic often used for skin and urinary tract infections (brand name Keflex)",
    "ceftriaxone": "a strong IV antibiotic used for serious infections (brand name Rocephin)",
    "vancomycin": "a powerful IV antibiotic used for serious resistant infections like MRSA",
    "piperacillin-tazobactam": "a broad-spectrum IV antibiotic for serious infections (brand name Zosyn)",
    "meropenem": "a powerful IV antibiotic reserved for the most resistant infections",
    "metronidazole": "an antibiotic used for abdominal and certain other infections (brand name Flagyl)",
    "fluconazole": "an antifungal medication (brand name Diflucan)",
    "prednisone": "a corticosteroid that reduces inflammation and suppresses the immune system",
    "dexamethasone": "a strong corticosteroid used to reduce inflammation",
    "methylprednisolone": "a corticosteroid given by IV for strong anti-inflammatory effect (brand name Solu-Medrol)",
    "albuterol": "a fast-acting inhaler that opens the airways during breathing difficulty",
    "ipratropium": "an inhaled medication that opens the airways (often combined with albuterol)",
    "tiotropium": "a long-acting inhaler for COPD (brand name Spiriva)",
    "nitroglycerin": "a medication that opens blood vessels to relieve chest pain",
    "hydralazine": "a medication that lowers blood pressure by relaxing blood vessels",
    "digoxin": "a heart medication that slows heart rate and helps the heart pump (brand name Lanoxin)",
    "amiodarone": "a medication used to treat dangerous irregular heart rhythms",
    "levothyroxine": "a thyroid hormone replacement medication (brand name Synthroid)",
    "docusate": "a stool softener (brand name Colace)",
    "polyethylene glycol": "an osmotic laxative used for constipation (brand name MiraLAX)",
    "lactulose": "a laxative also used to treat confusion caused by liver disease",
    "naloxone": "a medication that reverses opioid overdose (brand name Narcan)",
    "epinephrine": "a medication used for severe allergic reactions and cardiac arrest (adrenaline)",
    "norepinephrine": "a medication given by IV to raise dangerously low blood pressure",
    "phenylephrine": "a medication used to raise blood pressure or reduce nasal congestion",
    "propofol": "a medication used for sedation during procedures and in the ICU",

    # =================================================================
    # 3. CLINICAL PHRASES FROM DISCHARGE PAPERS (70+)
    # =================================================================
    "cleared for discharge": "the doctors have determined it is safe for you to go home",
    "medically optimized": "your medical condition has been treated as much as possible in the hospital",
    "activity as tolerated": "you may do as much physical activity as you feel comfortable doing",
    "resume home medications": "start taking all of your regular medications again",
    "continue current medications": "keep taking the same medications you are on now",
    "hold medications": "temporarily stop taking the listed medications",
    "taper off": "gradually reduce the dose of a medication before stopping it",
    "wean off": "slowly reduce and stop a medication or treatment",
    "titrate to effect": "adjust the medication dose until it works well for you",
    "self-limiting": "the condition will get better on its own without treatment",
    "benign": "not harmful or cancerous",
    "unremarkable": "normal, nothing abnormal was found",
    "within normal limits": "the test results are in the normal range",
    "grossly normal": "appears normal on basic examination",
    "clinically significant": "important enough to affect your health or treatment",
    "clinically stable": "your condition is not getting worse",
    "medically stable": "your vital signs and condition are steady and safe",
    "stable for transfer": "safe to be moved to another facility or unit",
    "no acute findings": "nothing new or urgent was found",
    "no acute process": "no new or sudden medical problem found",
    "no evidence of": "tests did not show signs of",
    "negative for": "the test did not find",
    "positive for": "the test did find",
    "incidental finding": "something found by chance that was not related to the reason for the test",
    "return precautions": "reasons you should come back to the emergency room",
    "seek immediate medical attention if": "go to the emergency room right away if",
    "follow up with your PCP within 1 week": "see your regular doctor within one week",
    "return to the ED if symptoms worsen": "come back to the emergency room if you feel worse",
    "elevate the affected extremity": "raise the injured arm or leg above heart level to reduce swelling",
    "apply ice for 20 minutes every 2 hours": "put ice on the area for 20 minutes at a time, every 2 hours",
    "keep the incision clean and dry": "do not get the surgical wound wet and keep it free of dirt",
    "no heavy lifting over 10 pounds for 6 weeks": "do not lift anything heavier than 10 pounds for 6 weeks",
    "no driving while taking narcotic pain medications": "do not drive while you are taking opioid pain medicine",
    "may shower 48 hours after surgery": "you can take a shower 2 days after your surgery",
    "no submerging the wound in water": "do not soak the wound in a bath, pool, or hot tub",
    "steri-strips will fall off on their own": "the small tape strips on your wound will come off by themselves",
    "wound care": "instructions for taking care of a surgical site or injury",
    "dressing change": "removing and replacing the bandage on a wound",
    "wet-to-dry dressing": "a wound bandage that is applied wet and removed dry to help clean the wound",
    "negative pressure wound therapy": "a vacuum device placed over a wound to help it heal faster",
    "soft diet": "eat only soft, easy-to-chew foods",
    "clear liquid diet": "drink only clear fluids like water, broth, juice, and gelatin",
    "full liquid diet": "consume only liquids and smooth foods like soup, pudding, and milkshakes",
    "mechanical soft diet": "eat only food that is soft and easy to chew, avoiding tough or crunchy items",
    "cardiac diet": "a heart-healthy diet low in salt, saturated fat, and cholesterol",
    "renal diet": "a kidney-friendly diet low in sodium, potassium, and phosphorus",
    "diabetic diet": "a diet focused on controlling blood sugar with balanced meals",
    "low-sodium diet": "limit salt intake to help control blood pressure and fluid retention",
    "fall precautions": "safety measures to prevent the patient from falling",
    "aspiration precautions": "safety measures to prevent food or liquid from going into the lungs",
    "contact precautions": "wear gloves and gown when entering the patient's room to prevent spread of infection",
    "droplet precautions": "wear a mask near the patient to prevent spread of infection through coughing or sneezing",
    "isolation precautions": "special safety steps to prevent spreading infection to others",
    "restraints": "devices used to limit a patient's movement for their own safety",
    "oxygen therapy": "providing extra oxygen through a mask or nasal tube to help breathing",
    "nasal cannula": "a small tube that rests under the nose to deliver extra oxygen",
    "non-rebreather mask": "a face mask that delivers a high concentration of oxygen",
    "high-flow nasal cannula": "a device that delivers a large amount of heated, humidified oxygen through the nose",
    "BiPAP": "a breathing machine that pushes air into the lungs to help with breathing",
    "CPAP": "continuous positive airway pressure, a machine that keeps the airway open during sleep",
    "disposition": "the plan for where the patient will go after leaving the hospital",
    "discharge to home": "the patient is going home",
    "discharge to rehab": "the patient is going to a rehabilitation facility for recovery",
    "discharge to SNF": "the patient is going to a skilled nursing facility for additional care",
    "AMA discharge": "the patient is leaving the hospital against the doctor's recommendation",
    "condition on discharge: stable": "the patient's condition was steady when they left the hospital",
    "condition on discharge: improved": "the patient's condition was better than when they arrived",

    # =================================================================
    # 4. MORE CONDITIONS AND DIAGNOSES (90+)
    # =================================================================
    "UTI": "urinary tract infection (a bladder or kidney infection)",
    "urinary tract infection": "an infection in the bladder or kidneys causing pain and frequent urination",
    "GERD": "gastroesophageal reflux disease (chronic acid reflux or heartburn)",
    "gastroesophageal reflux": "stomach acid flowing back up into the esophagus causing heartburn",
    "BPH": "benign prostatic hyperplasia (an enlarged prostate gland that is not cancer)",
    "CAD": "coronary artery disease (blocked or narrowed heart arteries)",
    "coronary artery disease": "a condition where the arteries supplying the heart become narrowed or blocked by plaque",
    "PVD": "peripheral vascular disease (poor blood flow to the legs and feet)",
    "PAD": "peripheral artery disease (narrowed arteries reducing blood flow to the legs)",
    "AAA": "abdominal aortic aneurysm (a dangerous bulge in the main artery in the belly)",
    "AFib": "atrial fibrillation (irregular heart rhythm)",
    "SVT": "supraventricular tachycardia (a fast heart rhythm that starts in the upper heart chambers)",
    "CHB": "complete heart block (the electrical signal between the upper and lower heart chambers is completely blocked)",
    "VTE": "venous thromboembolism (blood clots in veins, including leg clots and lung clots)",
    "ACS": "acute coronary syndrome (sudden reduced blood flow to the heart, including heart attacks)",
    "MVP": "mitral valve prolapse (a heart valve that does not close properly)",
    "PFO": "patent foramen ovale (a small hole between the upper heart chambers that did not close after birth)",
    "RBBB": "right bundle branch block (a delay in electrical signals on the right side of the heart)",
    "LBBB": "left bundle branch block (a delay in electrical signals on the left side of the heart)",
    "HTN": "hypertension (high blood pressure)",
    "DM": "diabetes mellitus (diabetes)",
    "DM1": "type 1 diabetes (the body cannot make insulin)",
    "DM2": "type 2 diabetes (the body does not use insulin properly)",
    "HLD": "hyperlipidemia (high cholesterol)",
    "hyperlipidemia": "high levels of cholesterol and fats in the blood",
    "hypothyroidism": "an underactive thyroid gland that does not produce enough hormones",
    "hyperthyroidism": "an overactive thyroid gland that produces too many hormones",
    "Graves' disease": "an autoimmune condition that causes the thyroid to be overactive",
    "Hashimoto's thyroiditis": "an autoimmune condition that slowly damages the thyroid gland",
    "PCOS": "polycystic ovary syndrome, a hormonal condition that can cause irregular periods and fertility problems",
    "OSA": "obstructive sleep apnea (breathing repeatedly stops and starts during sleep)",
    "MRSA": "a type of staph bacteria that is resistant to many common antibiotics",
    "VRE": "vancomycin-resistant enterococcus, a bacteria resistant to the antibiotic vancomycin",
    "C. diff": "Clostridioides difficile, a bacterial infection causing severe diarrhea often after antibiotic use",
    "Clostridium difficile": "a bacteria that causes severe diarrhea and colon inflammation, often after antibiotics",
    "bacteremia": "bacteria in the bloodstream",
    "fungemia": "fungal infection in the bloodstream",
    "meningitis": "inflammation of the membranes surrounding the brain and spinal cord",
    "encephalitis": "inflammation of the brain itself, usually from a viral infection",
    "pyelonephritis": "a kidney infection",
    "cholangitis": "an infection of the bile duct",
    "endometritis": "an infection of the lining of the uterus",
    "empyema": "a pocket of pus in the space between the lung and chest wall",
    "necrotizing fasciitis": "a life-threatening infection that rapidly destroys skin, fat, and tissue",
    "gangrene": "death of body tissue due to lack of blood flow or severe infection",
    "rhabdomyolysis": "a dangerous breakdown of muscle tissue that can damage the kidneys",
    "compartment syndrome": "dangerous pressure buildup inside a muscle group that cuts off blood flow",
    "pulmonary hypertension": "high blood pressure in the arteries of the lungs",
    "cor pulmonale": "right-sided heart failure caused by lung disease",
    "bronchitis": "inflammation of the airways in the lungs causing coughing",
    "bronchiectasis": "permanent widening of the airways causing chronic cough and mucus buildup",
    "pulmonary fibrosis": "scarring of the lung tissue that makes breathing difficult",
    "sarcoidosis": "a disease causing small clumps of inflammatory cells in the lungs and other organs",
    "tuberculosis": "a serious bacterial infection that mainly affects the lungs",
    "TB": "tuberculosis, a serious lung infection that can spread to others",
    "influenza": "the flu, a contagious viral respiratory infection",
    "COVID-19": "a respiratory illness caused by the SARS-CoV-2 virus",
    "Crohn's disease": "a chronic inflammatory bowel disease that can affect any part of the digestive tract",
    "ulcerative colitis": "a chronic inflammatory bowel disease affecting the large intestine",
    "IBD": "inflammatory bowel disease (Crohn's disease or ulcerative colitis)",
    "IBS": "irritable bowel syndrome, a condition causing belly pain, bloating, and changes in bowel habits",
    "GIST": "gastrointestinal stromal tumor, a type of tumor in the digestive tract",
    "GI bleed": "bleeding somewhere in the digestive tract",
    "upper GI bleed": "bleeding from the esophagus, stomach, or upper small intestine",
    "lower GI bleed": "bleeding from the lower small intestine, colon, or rectum",
    "peptic ulcer": "a sore in the lining of the stomach or upper small intestine",
    "gastritis": "inflammation of the stomach lining",
    "esophagitis": "inflammation of the esophagus (the tube from mouth to stomach)",
    "SBO": "small bowel obstruction (a blockage in the small intestine)",
    "large bowel obstruction": "a blockage in the large intestine preventing stool from passing",
    "GIB": "gastrointestinal bleeding",
    "NAFLD": "non-alcoholic fatty liver disease (fat buildup in the liver not caused by alcohol)",
    "NASH": "non-alcoholic steatohepatitis (fatty liver with inflammation and liver damage)",
    "portal hypertension": "high blood pressure in the vein that carries blood to the liver",
    "esophageal varices": "swollen veins in the esophagus caused by liver disease that can bleed dangerously",
    "lupus": "systemic lupus erythematosus, an autoimmune disease where the body attacks its own tissues",
    "SLE": "systemic lupus erythematosus, an autoimmune disease affecting many organs",
    "rheumatoid arthritis": "an autoimmune disease causing painful joint inflammation",
    "gout": "a type of arthritis caused by uric acid crystals building up in a joint",
    "fibromyalgia": "a condition causing widespread body pain, tiredness, and tenderness",
    "multiple sclerosis": "a disease where the immune system attacks the protective covering of nerves",
    "MS": "multiple sclerosis, an autoimmune disease affecting the brain and spinal cord",
    "Parkinson's disease": "a brain disorder causing tremors, stiffness, and difficulty with movement",
    "Alzheimer's disease": "a progressive brain disease causing memory loss and confusion",
    "dementia": "a decline in memory, thinking, and reasoning severe enough to interfere with daily life",
    "delirium": "sudden confusion and rapid changes in thinking, often caused by illness or medication",
    "psoriasis": "a skin condition causing red, scaly patches",
    "eczema": "a skin condition causing itchy, inflamed, and dry patches",
    "dermatitis": "inflammation of the skin causing redness and itching",
    "pressure ulcer": "a skin sore caused by prolonged pressure on the skin (also called a bedsore)",
    "decubitus ulcer": "a bedsore caused by lying or sitting in one position too long",
    "diabetic foot ulcer": "an open sore on the foot caused by diabetes-related nerve and blood vessel damage",
    "venous stasis ulcer": "a leg wound caused by poor blood return through the veins",
    "lymphedema": "swelling in an arm or leg caused by a blockage in the lymphatic system",

    # =================================================================
    # 5. SURGICAL AND PROCEDURAL TERMS (70+)
    # =================================================================
    "laparoscopic": "done through small incisions using a camera (minimally invasive surgery)",
    "open surgery": "surgery done through a larger incision to directly access the area",
    "robotic-assisted surgery": "surgery done with robotic tools controlled by the surgeon for greater precision",
    "minimally invasive": "a procedure done through small incisions rather than a large opening",
    "exploratory laparotomy": "opening the abdomen to look for and treat the source of a problem",
    "hernia repair": "surgery to fix tissue that is pushing through a weak spot in the muscle",
    "hemorrhoidectomy": "surgery to remove hemorrhoids",
    "fistulotomy": "surgery to open and drain an abnormal tunnel between two body parts",
    "fistula repair": "surgery to close an abnormal connection between two body parts",
    "colostomy": "surgery to bring the large intestine to an opening in the belly to bypass the rectum",
    "ileostomy": "surgery to bring the small intestine to an opening in the belly for waste to exit",
    "ostomy": "a surgically created opening in the belly for waste to leave the body into a bag",
    "gastric bypass": "weight loss surgery that makes the stomach smaller and reroutes the intestines",
    "sleeve gastrectomy": "weight loss surgery that removes most of the stomach",
    "Nissen fundoplication": "surgery to treat acid reflux by wrapping the top of the stomach around the esophagus",
    "Whipple procedure": "a major surgery to remove part of the pancreas, small intestine, and bile duct (for cancer)",
    "splenectomy": "surgery to remove the spleen",
    "adrenalectomy": "surgery to remove an adrenal gland",
    "orchiectomy": "surgery to remove one or both testicles",
    "oophorectomy": "surgery to remove one or both ovaries",
    "salpingectomy": "surgery to remove a fallopian tube",
    "D&C": "dilation and curettage, a procedure to remove tissue from inside the uterus",
    "C-section": "cesarean section, delivering a baby through a surgical cut in the belly and uterus",
    "episiotomy": "a surgical cut made during childbirth to widen the vaginal opening",
    "TURP": "transurethral resection of the prostate, a surgery to remove prostate tissue blocking urine flow",
    "lithotripsy": "using shock waves to break up kidney stones into small pieces",
    "ureteral stent placement": "placing a small tube in the ureter to keep it open for urine to flow from kidney to bladder",
    "AV fistula creation": "surgery to connect an artery and vein in the arm for dialysis access",
    "port placement": "surgically placing a small device under the skin for easy IV access for chemotherapy",
    "central line placement": "inserting a special IV catheter into a large vein for medications and fluids",
    "PICC line": "a long IV line inserted through the arm vein and threaded to a large vein near the heart",
    "arterial line": "a thin tube placed in an artery to continuously monitor blood pressure",
    "chest tube insertion": "placing a tube between the ribs to drain air or fluid from around the lung",
    "G-tube placement": "surgically placing a feeding tube directly into the stomach through the belly",
    "PEG tube": "a feeding tube placed through the skin into the stomach",
    "J-tube": "a feeding tube placed directly into the small intestine",
    "NG tube": "a tube inserted through the nose into the stomach to drain or deliver nutrition",
    "nasogastric tube": "a tube passed through the nose into the stomach",
    "Foley catheter": "a tube inserted into the bladder to drain urine",
    "suprapubic catheter": "a tube placed through the lower belly directly into the bladder to drain urine",
    "wound vac": "a device that uses suction to help wounds heal faster",
    "skin graft": "taking healthy skin from one area and placing it over a wound to help it heal",
    "flap surgery": "moving living tissue with its blood supply from one part of the body to another",
    "ORIF": "open reduction and internal fixation, surgery to set a broken bone and hold it together with metal hardware",
    "closed reduction": "setting a broken bone or dislocated joint back into place without surgery",
    "external fixation": "using a metal frame outside the body attached by pins to hold broken bones in place",
    "intramedullary nail": "a metal rod placed inside the hollow center of a bone to hold a fracture together",
    "hardware removal": "surgery to remove plates, screws, or rods that were used to fix a broken bone",
    "ACL reconstruction": "surgery to rebuild the torn anterior cruciate ligament in the knee",
    "rotator cuff repair": "surgery to fix torn tendons in the shoulder",
    "carpal tunnel release": "surgery to relieve pressure on the nerve in the wrist",
    "spinal fusion": "surgery to permanently connect two or more bones in the spine",
    "vertebroplasty": "injecting bone cement into a fractured spine bone to stabilize it",
    "kyphoplasty": "a procedure to restore the height of a collapsed spine bone using a balloon and cement",
    "cranioplasty": "surgery to repair a defect or hole in the skull",
    "VP shunt": "a tube placed from the brain to the belly to drain excess fluid (for hydrocephalus)",
    "tonsillectomy": "surgery to remove the tonsils",
    "adenoidectomy": "surgery to remove the adenoids",
    "septoplasty": "surgery to straighten the wall between the nostrils to improve breathing",
    "FESS": "functional endoscopic sinus surgery, using a camera to open blocked sinuses",
    "tympanoplasty": "surgery to repair a hole in the eardrum",
    "cataract surgery": "surgery to remove a clouded lens in the eye and replace it with a clear artificial lens",
    "vitrectomy": "surgery to remove the gel from inside the eye to treat retinal problems",
    "amputation": "surgical removal of a limb or part of a limb",
    "sentinel lymph node biopsy": "removing the first lymph node where cancer would likely spread to check for cancer",
    "lymph node dissection": "surgery to remove lymph nodes to check for or treat cancer spread",
    "Mohs surgery": "a precise skin cancer surgery that removes one thin layer at a time until no cancer remains",
    "radiation therapy": "using high-energy beams to kill cancer cells",
    "brachytherapy": "placing radioactive material inside the body next to a tumor to kill cancer cells",

    # =================================================================
    # 6. RADIOLOGY AND IMAGING TERMS (40+)
    # =================================================================
    "radiolucent": "an area that appears dark on an X-ray (lets X-rays pass through, like air or soft tissue)",
    "radiopaque": "an area that appears white on an X-ray (blocks X-rays, like bone or metal)",
    "lucency": "a dark area on an X-ray or CT that may indicate a cyst, cavity, or bone loss",
    "opacity": "a white or cloudy area on an X-ray that may indicate fluid, tissue, or a mass",
    "consolidation": "a dense white area in the lung on X-ray, often indicating pneumonia or fluid",
    "ground-glass opacity": "a hazy, cloudy area in the lungs on a CT scan that can indicate infection or inflammation",
    "infiltrate": "an abnormal substance or fluid seen in the lungs on imaging, often from infection",
    "nodule": "a small round spot found on imaging, which may or may not be concerning",
    "pulmonary nodule": "a small round spot on the lung seen on imaging that needs monitoring for cancer",
    "mass": "a large abnormal growth found on imaging that may need biopsy",
    "lesion": "an abnormal area of tissue found on imaging or examination",
    "calcification": "a deposit of calcium in tissue, seen as a bright white spot on imaging",
    "herniation": "tissue or an organ pushing through an opening where it does not belong",
    "disc herniation": "a spinal disc bulging out of its normal position, possibly pressing on a nerve",
    "effacement": "the normal space around a structure being pushed away or flattened, often by swelling",
    "midline shift": "the brain being pushed to one side, a sign of dangerous pressure inside the skull",
    "hydrocephalus": "excess fluid buildup inside the brain causing increased pressure",
    "enhancement": "an area that lights up brighter on imaging after contrast dye is given, which can indicate active disease",
    "contrast": "a special dye used during imaging tests to make certain areas show up more clearly",
    "contrast-enhanced": "an imaging scan done with special dye injected to see more detail",
    "non-contrast": "an imaging scan done without special dye",
    "filling defect": "a blockage seen inside a blood vessel or hollow organ on imaging, often a blood clot",
    "thrombus": "a blood clot seen on imaging",
    "dissection": "a tear in the wall of a blood vessel seen on imaging",
    "perfusion defect": "an area that is not receiving normal blood flow on a specialized scan",
    "ischemic changes": "signs on imaging that an area is not getting enough blood",
    "infarct": "an area of tissue death caused by loss of blood supply, seen on imaging",
    "acute infarct": "a newly occurred area of tissue death from sudden loss of blood flow",
    "chronic changes": "findings on imaging that have been present for a long time and are not new",
    "degenerative changes": "wear-and-tear changes in bones and joints seen on imaging, common with aging",
    "spondylosis": "age-related wear and tear of the spinal bones and discs",
    "spondylolisthesis": "one spine bone slipping forward over the one below it",
    "compression fracture": "a spine bone that has collapsed, often from osteoporosis",
    "pathologic fracture": "a bone break caused by disease (like cancer) weakening the bone rather than injury",
    "avulsion fracture": "a small piece of bone pulled off where a tendon or ligament attaches",
    "comminuted fracture": "a bone broken into three or more pieces",
    "displaced fracture": "a broken bone where the pieces have moved out of alignment",
    "non-displaced fracture": "a broken bone where the pieces are still in the correct position",
    "stress fracture": "a tiny crack in a bone caused by repetitive force or overuse",
    "free fluid": "loose fluid seen in the belly or chest on imaging, which can indicate bleeding or infection",
    "free air": "air seen outside the intestines in the belly on imaging, which can mean a hole in the bowel",
    "pneumoperitoneum": "free air in the abdominal cavity, often indicating a perforation in the bowel",
    "bowel wall thickening": "the intestine wall appearing thicker than normal on imaging, suggesting inflammation or infection",
    "fat stranding": "haziness around an organ on a CT scan indicating nearby inflammation",
    "lymphadenopathy": "enlarged lymph nodes seen on imaging",
    "hepatomegaly": "an enlarged liver",
    "splenomegaly": "an enlarged spleen",
    "cardiomegaly": "an enlarged heart seen on chest X-ray",
    "mediastinal widening": "the center area of the chest appearing wider than normal on X-ray, which may indicate a serious condition",

    # =================================================================
    # 7. ADDITIONAL LABS, VITALS, AND NURSING TERMS (60+)
    # =================================================================
    "lactic acid": "a substance in the blood that rises when the body is not getting enough oxygen",
    "procalcitonin": "a blood test that helps determine if an infection is caused by bacteria",
    "D-dimer": "a blood test that can help rule out blood clots",
    "fibrinogen": "a protein that helps the blood clot, measured to check for clotting problems",
    "lipase": "an enzyme that rises in the blood when the pancreas is inflamed",
    "amylase": "an enzyme that can rise in the blood with pancreas problems",
    "uric acid": "a waste product that can build up and cause gout or kidney stones",
    "TSH": "thyroid-stimulating hormone, a blood test to check how well the thyroid is working",
    "T4": "thyroxine, a thyroid hormone measured to check thyroid function",
    "ferritin": "a blood test that measures iron stores in the body",
    "transferrin": "a protein that carries iron in the blood",
    "TIBC": "total iron-binding capacity, a blood test that helps diagnose iron deficiency",
    "reticulocyte count": "a blood test measuring young red blood cells to see if the bone marrow is making enough",
    "blood type and screen": "a blood test to determine your blood type before a potential transfusion",
    "type and crossmatch": "a blood test to make sure donated blood is compatible with yours before a transfusion",
    "coagulation panel": "a set of blood tests measuring how well the blood clots",
    "PTT": "partial thromboplastin time, a blood test measuring how long it takes blood to clot",
    "aPTT": "activated partial thromboplastin time, a test to monitor blood thinners like heparin",
    "sed rate": "sedimentation rate, a blood test for inflammation",
    "ANA": "antinuclear antibody, a blood test used to check for autoimmune diseases",
    "rheumatoid factor": "a blood test used to help diagnose rheumatoid arthritis",
    "HCG": "human chorionic gonadotropin, a hormone measured to confirm pregnancy",
    "brain natriuretic peptide": "a blood marker that rises when the heart is under strain, used to check for heart failure",
    "pro-BNP": "a blood marker that helps diagnose and monitor heart failure",
    "NT-proBNP": "a blood test that indicates how hard the heart is working (higher means worse heart failure)",
    "magnesium level": "a blood test measuring magnesium, important for heart and muscle function",
    "phosphorus level": "a blood test measuring phosphorus, important for bones and energy",
    "calcium level": "a blood test measuring calcium, important for bones, muscles, and nerves",
    "sodium level": "a blood test measuring sodium, important for fluid balance",
    "potassium level": "a blood test measuring potassium, important for heart and muscle function",
    "chloride level": "a blood test measuring chloride, which helps maintain fluid balance",
    "CO2 level": "a blood test measuring carbon dioxide, which reflects how well the lungs and kidneys are working",
    "glucose level": "a blood test measuring current blood sugar",
    "fasting glucose": "a blood sugar test taken when you have not eaten for at least 8 hours",
    "hemoglobin A1C": "a blood test showing your average blood sugar over the past 3 months",
    "GFR": "glomerular filtration rate, a measure of how well the kidneys are filtering blood",
    "trough level": "the lowest level of a medication in the blood, measured just before the next dose",
    "peak level": "the highest level of a medication in the blood after a dose",
    "therapeutic level": "the medication level is in the effective range in the blood",
    "subtherapeutic": "the medication level in the blood is too low to be effective",
    "supratherapeutic": "the medication level in the blood is too high and could be harmful",
    "telemetry": "continuous heart rhythm monitoring using wireless sensors",
    "pulse oximetry": "measuring blood oxygen levels using a clip on the finger",
    "capnography": "monitoring the level of carbon dioxide in exhaled breath",
    "central venous pressure": "a measurement of pressure in the large veins near the heart, used to check fluid status",
    "CVP": "central venous pressure, a measure of how much fluid is in the circulatory system",
    "Swan-Ganz catheter": "a special catheter placed in the heart to measure pressures and blood flow",
    "arterial blood gas": "a blood test from an artery measuring oxygen, carbon dioxide, and acid levels",
    "venous blood gas": "a blood test from a vein measuring carbon dioxide and acid levels",
    "point-of-care testing": "a quick bedside test done at the patient's side for rapid results",
    "blood smear": "looking at blood cells under a microscope to check for abnormalities",
    "Coombs test": "a blood test to see if the immune system is attacking red blood cells",
    "stool guaiac": "a test to check for hidden blood in the stool",
    "fecal occult blood test": "a test to detect hidden blood in the stool that you cannot see",
    "wound culture": "a test where a sample from a wound is grown in a lab to identify the bacteria causing infection",

    # =================================================================
    # 8. ADDITIONAL ANATOMY AND PHYSICAL EXAM TERMS (65+)
    # =================================================================
    "dorsal": "the back side of the body or top of the hand/foot",
    "ventral": "the front side of the body",
    "supine": "lying face up on the back",
    "prone": "lying face down on the stomach",
    "Trendelenburg": "lying on the back with feet raised higher than the head",
    "Fowler's position": "sitting up in bed at a 45-to-60 degree angle",
    "contralateral": "on the opposite side of the body",
    "ipsilateral": "on the same side of the body",
    "periumbilical": "around the belly button",
    "costal": "relating to the ribs",
    "subcostal": "below the ribs",
    "intercostal": "between the ribs",
    "supraclavicular": "above the collarbone",
    "axillary": "in the armpit area",
    "inguinal": "in the groin area",
    "popliteal": "behind the knee",
    "plantar": "the bottom (sole) of the foot",
    "palmar": "the palm side of the hand",
    "occipital": "the back of the head",
    "temporal": "the side of the head near the temple",
    "parietal": "the top and sides of the skull",
    "frontal": "the forehead area",
    "midline": "the center line of the body",
    "flank": "the side of the body between the ribs and hip",
    "perineal": "the area between the genitals and anus",
    "sacroiliac": "the joint where the spine meets the pelvis",
    "auscultation": "listening to sounds inside the body using a stethoscope",
    "palpation": "examining the body by pressing and feeling with the hands",
    "percussion": "tapping on the body and listening to the sounds to check for fluid or air",
    "inspection": "looking at the body for visible signs of disease or injury",
    "crepitus": "a crackling or grinding sound or feeling in a joint or under the skin",
    "guarding": "tensing the belly muscles during examination, often a sign of pain or inflammation inside",
    "rebound tenderness": "pain that gets worse when the doctor releases pressure on the belly, a sign of inflammation",
    "rigidity": "the belly muscles being very stiff and board-like, a sign of a serious abdominal problem",
    "distension": "the belly appearing swollen or bloated",
    "Murphy's sign": "pain when pressing under the right ribcage while breathing in, suggesting gallbladder inflammation",
    "McBurney's point tenderness": "pain at a specific spot in the right lower belly, suggesting appendicitis",
    "Babinski sign": "an abnormal reflex in the foot suggesting a problem with the brain or spinal cord",
    "Romberg test": "a balance test where the patient stands with eyes closed",
    "Kernig's sign": "pain when straightening the leg while the hip is bent, a sign of possible meningitis",
    "Brudzinski's sign": "the knees bending when the neck is flexed forward, a sign of possible meningitis",
    "clubbing": "rounding and widening of the fingertips, which can indicate heart or lung disease",
    "pitting edema": "swelling that leaves a dent when you press on it with a finger",
    "non-pitting edema": "firm swelling that does not leave a dent when pressed",
    "murmur": "an extra or unusual heart sound that may indicate a heart valve problem",
    "gallop": "an extra heart sound that can indicate heart failure",
    "bruit": "a whooshing sound heard over a blood vessel indicating turbulent blood flow or narrowing",
    "rales": "crackling sounds in the lungs heard with a stethoscope, often indicating fluid",
    "crackles": "crackling sounds in the lungs, often a sign of fluid or infection",
    "rhonchi": "low-pitched rumbling sounds in the lungs from mucus in the airways",
    "diminished breath sounds": "the lungs sound quieter than normal, which may indicate fluid, air, or collapse",
    "absent breath sounds": "no lung sounds heard in an area, which may mean a collapsed lung or large fluid collection",
    "JVD": "jugular venous distension, visible bulging of the neck veins indicating heart failure or fluid overload",
    "hepatojugular reflux": "neck veins bulging when the doctor presses on the liver, a sign of heart failure",
    "capillary refill": "how quickly color returns to a fingertip after pressing it, checking blood flow",
    "pallor": "unusual paleness of the skin that may indicate anemia or poor blood flow",
    "ecchymosis": "a bruise, a discolored area of skin from bleeding underneath",
    "petechiae": "tiny red or purple dots on the skin from bleeding under the surface",
    "purpura": "purple spots on the skin caused by bleeding underneath",
    "erythema": "redness of the skin, often a sign of inflammation or infection",
    "induration": "an area of skin that feels hard or firm, often from inflammation or infection",
    "fluctuance": "a soft, wave-like feeling when pressing on a swelling, suggesting fluid or pus inside",
    "turgor": "skin elasticity checked by pinching, used to assess dehydration",
    "mottling": "blotchy, uneven coloring of the skin indicating poor blood flow",
    "diaphoretic": "sweating heavily, which can be a sign of a serious medical condition",
    "cachexia": "severe weight loss and muscle wasting from serious illness like cancer",
    "atrophy": "shrinking or wasting away of a body part or tissue",
    "hypertrophy": "enlargement or thickening of a body part or tissue",
}
