"""Extra medical terms for V2 training - abbreviations and phrases
that patients commonly see on discharge papers but aren't in our
main dictionary."""

import json

OUTPUT = "./medclear_results/training_v2/extra_terms.jsonl"

EXTRA_TERMS = {
    # === ABBREVIATIONS patients see on discharge papers ===
    "SOB": "shortness of breath",
    "DOE": "shortness of breath with activity",
    "CP": "chest pain",
    "HA": "headache",
    "N/V": "nausea and vomiting",
    "N/V/D": "nausea, vomiting, and diarrhea",
    "BLE": "both legs",
    "BUE": "both arms",
    "RLE": "right leg",
    "LLE": "left leg",
    "RUE": "right arm",
    "LUE": "left arm",
    "UE": "upper extremity (arm)",
    "LE": "lower extremity (leg)",
    "ROM": "range of motion (how far a joint can move)",
    "FWW": "front-wheeled walker",
    "ADLs": "activities of daily living (bathing, dressing, eating, toileting)",
    "PMH": "past medical history",
    "PSH": "past surgical history",
    "FH": "family history",
    "SH": "social history",
    "HPI": "history of present illness (the story of the current problem)",
    "ROS": "review of systems (a checklist of symptoms in each body system)",
    "PE": "physical examination",
    "A&P": "assessment and plan",
    "CC": "chief complaint (the main reason for the visit)",
    "Dx": "diagnosis",
    "Tx": "treatment",
    "Rx": "prescription",
    "Hx": "history",
    "Sx": "symptoms",
    "Fx": "fracture (broken bone)",
    "Bx": "biopsy (tissue sample for testing)",
    "Cx": "culture (lab test growing bacteria to identify infection)",
    "Abx": "antibiotics",
    "Meds": "medications",
    "Pt": "patient",
    "yo": "years old",
    "y/o": "years old",
    "M": "male",
    "F": "female",
    "c/o": "complaining of",
    "d/t": "due to",
    "w/": "with",
    "w/o": "without",
    "r/o": "rule out (check if a condition is present)",
    "NAD": "no acute distress (patient looks comfortable)",
    "WNL": "within normal limits (normal)",
    "VSS": "vital signs stable",
    "AAOx3": "awake, alert, and oriented to person, place, and time",
    "NKDA": "no known drug allergies",
    "NKA": "no known allergies",
    "OTC": "over-the-counter (no prescription needed)",
    "D/C": "discharge (leaving the hospital) or discontinue (stop taking)",
    "AMA": "against medical advice (leaving the hospital against doctor recommendation)",
    "SNF": "skilled nursing facility (nursing home with medical care)",
    "LTAC": "long-term acute care facility",
    "rehab": "rehabilitation center for recovery after illness or surgery",
    "ICU": "intensive care unit (for the most critically ill patients)",
    "CCU": "cardiac care unit (ICU for heart patients)",
    "NICU": "neonatal intensive care unit (ICU for newborn babies)",
    "PICU": "pediatric intensive care unit (ICU for children)",
    "ED": "emergency department",
    "ER": "emergency room",
    "OR": "operating room",
    "PACU": "post-anesthesia care unit (recovery room after surgery)",
    "pre-op": "before surgery",
    "post-op": "after surgery",
    "intra-op": "during surgery",

    # === COMMON MEDICATIONS patients see ===
    "aspirin": "a blood-thinning and pain-relieving medication",
    "ibuprofen": "an anti-inflammatory pain reliever (Advil, Motrin)",
    "acetaminophen": "a pain and fever reducer (Tylenol)",
    "naproxen": "an anti-inflammatory pain reliever (Aleve)",
    "oxycodone": "a strong opioid pain medication",
    "hydrocodone": "a strong opioid pain medication (often combined with Tylenol)",
    "morphine": "a strong opioid pain medication",
    "tramadol": "a moderate-strength pain medication",
    "gabapentin": "a medication for nerve pain and seizures",
    "pregabalin": "a medication for nerve pain (Lyrica)",
    "cyclobenzaprine": "a muscle relaxant (Flexeril)",
    "lisinopril": "a blood pressure medication (ACE inhibitor)",
    "losartan": "a blood pressure medication (ARB)",
    "amlodipine": "a blood pressure medication (calcium channel blocker)",
    "metoprolol": "a heart rate and blood pressure medication (beta-blocker)",
    "carvedilol": "a heart rate and blood pressure medication (Coreg)",
    "atorvastatin": "a cholesterol-lowering medication (Lipitor)",
    "rosuvastatin": "a cholesterol-lowering medication (Crestor)",
    "metformin": "a diabetes medication that helps lower blood sugar",
    "glipizide": "a diabetes medication that helps the pancreas make more insulin",
    "empagliflozin": "a diabetes and heart medication (Jardiance)",
    "semaglutide": "a diabetes and weight loss medication (Ozempic, Wegovy)",
    "levothyroxine": "thyroid hormone replacement (Synthroid)",
    "omeprazole": "a stomach acid reducer (Prilosec)",
    "pantoprazole": "a stomach acid reducer (Protonix)",
    "furosemide": "a water pill that removes excess fluid (Lasix)",
    "spironolactone": "a mild water pill that also protects the heart",
    "hydrochlorothiazide": "a water pill for blood pressure",
    "warfarin": "a blood thinner that requires regular blood tests (Coumadin)",
    "apixaban": "a blood thinner that does not require regular blood tests (Eliquis)",
    "rivaroxaban": "a blood thinner (Xarelto)",
    "clopidogrel": "a blood thinner that prevents platelets from clumping (Plavix)",
    "ticagrelor": "a blood thinner used after heart stent placement (Brilinta)",
    "enoxaparin": "an injectable blood thinner (Lovenox)",
    "heparin": "an IV blood thinner used in the hospital",
    "amoxicillin": "a common antibiotic (penicillin family)",
    "azithromycin": "an antibiotic (Z-pack)",
    "ciprofloxacin": "a strong antibiotic (fluoroquinolone)",
    "doxycycline": "an antibiotic used for many types of infections",
    "cephalexin": "an antibiotic (Keflex)",
    "ceftriaxone": "a strong IV antibiotic",
    "vancomycin": "a powerful IV antibiotic for resistant infections like MRSA",
    "piperacillin-tazobactam": "a very strong IV antibiotic for serious infections (Zosyn)",
    "meropenem": "one of the strongest IV antibiotics, for drug-resistant infections",
    "fluconazole": "an antifungal medication (Diflucan)",
    "prednisone": "a steroid that reduces inflammation and suppresses the immune system",
    "methylprednisolone": "a strong steroid given by IV (Solu-Medrol)",
    "dexamethasone": "a potent steroid for inflammation",
    "albuterol": "an inhaler that opens the airways (rescue inhaler)",
    "fluticasone": "a steroid inhaler for asthma and allergies (Flovent, Flonase)",
    "montelukast": "an allergy and asthma medication (Singulair)",
    "sertraline": "an antidepressant (Zoloft, an SSRI)",
    "fluoxetine": "an antidepressant (Prozac, an SSRI)",
    "escitalopram": "an antidepressant (Lexapro, an SSRI)",
    "duloxetine": "an antidepressant that also helps with pain (Cymbalta)",
    "trazodone": "a medication for sleep and depression",
    "quetiapine": "a medication for mood, sleep, and psychosis (Seroquel)",
    "lorazepam": "an anti-anxiety and sedation medication (Ativan)",
    "diazepam": "an anti-anxiety and muscle relaxant medication (Valium)",
    "ondansetron": "an anti-nausea medication (Zofran)",
    "docusate": "a stool softener (Colace)",
    "senna": "a laxative for constipation",
    "polyethylene glycol": "a gentle laxative (MiraLAX)",
    "diphenhydramine": "an allergy and sleep medication (Benadryl)",
    "insulin glargine": "a long-acting insulin taken once daily (Lantus)",
    "insulin lispro": "a fast-acting insulin taken before meals (Humalog)",

    # === CONDITIONS patients commonly see ===
    "UTI": "urinary tract infection (bladder infection)",
    "URI": "upper respiratory infection (common cold)",
    "GERD": "gastroesophageal reflux disease (chronic acid reflux, heartburn)",
    "BPH": "benign prostatic hyperplasia (enlarged prostate, not cancer)",
    "CAD": "coronary artery disease (blocked or narrowed heart arteries)",
    "PVD": "peripheral vascular disease (poor blood flow to the legs)",
    "PAD": "peripheral artery disease (narrowed arteries in the legs)",
    "OSA": "obstructive sleep apnea (breathing stops during sleep)",
    "OA": "osteoarthritis (wear-and-tear joint disease)",
    "RA": "rheumatoid arthritis (autoimmune joint disease)",
    "DMII": "type 2 diabetes mellitus",
    "DM2": "type 2 diabetes",
    "DM1": "type 1 diabetes (autoimmune, requires insulin)",
    "HTN": "hypertension (high blood pressure)",
    "HLD": "hyperlipidemia (high cholesterol)",
    "A-fib": "atrial fibrillation (irregular heart rhythm)",
    "AFib": "atrial fibrillation (irregular heart rhythm)",
    "CHF": "congestive heart failure",
    "HFrEF": "heart failure with reduced pumping strength",
    "HFpEF": "heart failure with preserved pumping but stiff heart muscle",
    "ESRD": "end-stage renal disease (kidney failure needing dialysis)",
    "CKD": "chronic kidney disease",
    "AKI": "acute kidney injury (sudden kidney failure)",
    "COPD": "chronic obstructive pulmonary disease",
    "PE": "pulmonary embolism (blood clot in the lungs)",
    "DVT": "deep vein thrombosis (blood clot in a deep leg vein)",
    "CVA": "cerebrovascular accident (stroke)",
    "TIA": "transient ischemic attack (mini-stroke)",
    "SBO": "small bowel obstruction (blockage in the small intestine)",
    "LBO": "large bowel obstruction (blockage in the large intestine)",
    "PNA": "pneumonia (lung infection)",
    "MRSA": "methicillin-resistant Staphylococcus aureus (a drug-resistant staph infection)",
    "VRE": "vancomycin-resistant Enterococcus (a drug-resistant bacterial infection)",
    "C. diff": "Clostridioides difficile (a severe intestinal infection often caused by antibiotics)",
    "SBP": "spontaneous bacterial peritonitis (infection of belly fluid in liver disease)",
    "SIRS": "systemic inflammatory response syndrome (body-wide inflammation)",
    "DKA": "diabetic ketoacidosis (dangerous diabetes emergency)",
    "HHS": "hyperosmolar hyperglycemic state (dangerous high blood sugar in type 2 diabetes)",
    "GI bleed": "gastrointestinal bleeding (bleeding somewhere in the digestive tract)",
    "UGIB": "upper GI bleed (bleeding from the esophagus, stomach, or upper intestine)",
    "LGIB": "lower GI bleed (bleeding from the colon or rectum)",
}

pairs = []
for term, definition in EXTRA_TERMS.items():
    pairs.append({
        "input_text": f"define: {term}",
        "target": definition,
        "level": "term",
    })
    pairs.append({
        "input_text": f"what does {term} mean?",
        "target": definition,
        "level": "term",
    })

with open(OUTPUT, "w", encoding="utf-8") as f:
    for p in pairs:
        f.write(json.dumps(p, ensure_ascii=False) + "\n")

print(f"Generated {len(pairs)} term pairs from {len(EXTRA_TERMS)} terms")
print(f"Saved to {OUTPUT}")
